<?php if (isset($_SESSION['USERNAME'])) : ?>

    <h5 class="edit-title">Editar Noticia</h5>
    <form class="form-edit" action="editarNoticia/<?= $news->id ?>" method="POST">
        <div class="mb-3">
            <label for="" class="form-label">Título</label>
            <input name="title" type="text" value="<?= $news->titulo ?>" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Contenido</label>
            <input name="content" type="text" value="<?= $news->contenido ?>" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Fecha</label>
            <input name="date" type="date" value="<?= $news->fecha ?>" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Hora</label>
            <input name="hour" type="hour" value="<?= $news->hora ?>" class="form-control" required>
        </div>
        <div class="mb-3">
            <?php require 'templates/select.form.edit.phtml' ?>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    </div>
<?php endif; ?>