<footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
      <div class="align-items-center">
        <span class="text-muted">PORTAL DE NOTICIAS</span>
        <p class="fs-3"></p>
        <div class="align-items-center">
          <img src="./img/facebook.png" alt="">
          <img src="./img/youtube.png" alt="">
          <img src="./img/twitter.png" alt="">
          <img src="./img/instagram.png" alt="">
        </div>
      </div>
</footer>
  
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="./js/main.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
     
</body>
</html>