<!-- form para noticias -->

<form id="news-form" action="agregarNoticia" method="POST">

     <div class="mb-3">
          <label for="" class="form-label">Título de la noticia</label>
          <input name="title" type="text" class="form-control" required>
     </div>

     <div class="mb-3">
          <label for="" class="form-label">Contenido</label>
          <input name="content" type="text" class="form-control" required>
     </div>

     <div class="mb-3">
          <label for="" class="form-label">Fecha</label>
          <input name="date" type="date" class="form-control" required>

          <label for="" class="form-label">Hora</label>
          <input name="hour" type="hour" class="form-control" required>
     </div>

     <div class="mb-3">
          <label for="sections" class="form-label">Sección</label>
          <select name="id_section" id="sections" class="form-select" aria-label="Default select example" required>
               <?php foreach ($sections as $section) : ?>
                    <option value="<?= $section->id_seccion ?>">
                         <?= $section->nombre_seccion ?>
                    </option>
               <?php endforeach; ?>
          </select>
     </div>

     <div>
          <button type="submit" class="btn btn-success">Agregar</button>
          <button type="button" class="btn btn-danger" id="btn-cancelar">Cancelar</button>
     </div>
</form>

