<!-- form para secciones -->
<form action="agregar-seccion" method="POST" class="form-add-section">
     <h3>Agregar secciones</h3>
     <div class="mb-3">
          <label for="seccion-nombre" class="form-label">Nueva sección</label>
          <input class="form-control" type="text" name="section_name" placeholder="Nombre la nueva seccion" id="seccion-nombre" autocomplete="off" required>

     </div>
     <button type="submit" class="btn btn-success">Agregar</button>
</form>

<!-- form para noticias -->
<form id="news-form" action="agregar" method="POST">
     <h3>Agregar noticias</h3>

     <div class="mb-3">
          <label for="" class="form-label">Título de la noticia</label>
          <input name="title" type="text" class="form-control" autocomplete="off" required>
     </div>

     <div class="mb-3">

          <label class="form-label" for="textarea">Contenido</label>
          <textarea name="content" class="form-control" id="textarea" autocomplete="off" required></textarea>
     </div>

     <div class="mb-3">
          <label for="" class="form-label">Fecha</label>
          <input name="date" type="date" class="form-control" autocomplete="off" required>

          <label for="" class="form-label">Hora</label>
          <input name="hour" type="hour" class="form-control" autocomplete="off" required>
     </div>

     <div class="mb-3">
          <label for="sections" class="form-label">Sección</label>
          <select name="id_section" id="sections" class="form-select" aria-label="Default select example" required>
               <?php foreach ($sections as $section) : ?>
                    <option value="<?= $section->id_seccion ?>">
                         <?= $section->nombre_seccion ?>
                    </option>
               <?php endforeach; ?>
          </select>
     </div>

     <div>
          <button type="submit" class="btn btn-success">Agregar</button>
          <button type="button" class="btn btn-danger" id="btn-cancelar">Cancelar</button>
     </div>
</form>