<!-- form para secciones -->
<form action="agregar-seccion" method="POST">
     <div class="mb-3">
          <label for="seccion-nombre" class="form-label">Nueva sección</label>
          <input class="form-control" type="text" name="section-name" placeholder="Nombre la nueva seccion" id="seccion-nombre" required>
          <button type="submit" class="btn btn-success">Agregar</button>
          <a class="btn btn-secondary" href="listar-seccion">Lista de secciones</a>
     </div>

</form>