<?= AuthHelper::initiate_session() ?>
<!DOCTYPE html>
<html lang="en">

<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="./css/style.css">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
     <title>Noticias</title>
</head>

<body>


     <header>
          <nav class="navbar navbar-dark bg-dark">

               <a class="navbar-brand" href="listarNoticias">Portal de Noticias</a>
               <?php if(isset($_SESSION['USER_ID'])): ?>
               <h2 class="navbar-brand">Hola, <?=$_SESSION['USERNAME']?></h2>
               <?php else: ?>
               
               <?php endif; ?>
               <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarNav">  
                    <ul class="navbar-nav">
                         <?php require('./templates/lista.secciones.phtml'); ?>
                         <?php if(!isset($_SESSION['USER_ID'])): ?>
                              <li class="nav-item">
                                   <a class="nav-link" aria-current="page" href="login">Login</a>
                              </li>
                         <?php else: ?>
                              <li class="nav-item">
                                   <a class="nav-link" aria-current="page" href="logout">Logout</a>
                                   <a class="nav-link" aria-current="page" href="">Agregar noticias</a>
                              </li>
                         <?php endif ?>
                    </ul>
               </div>
          </nav>
     </header>


     <main>