<?= AuthHelper::initiate_session() ?>
<!DOCTYPE html>
<html lang="en">

<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="./css/style.css">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
     <title>Portal de Noticias</title>

     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>

<header>
     <nav class="navbar navbar-dark bg-dark">

          <a class="navbar-brand" href="../listar">Portal de Noticias</a>
          <?php if(isset($_SESSION['USER_ID'])): ?>
               <h2 class="navbar-brand">Hola, <?=$_SESSION['USERNAME']?></h2>
          <?php endif; ?>
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">  
               <ul class="navbar-nav">       

               <?php if(isset($sections)): ?>
                    <?php require('./templates/lista.secciones.phtml'); ?>
               <?php endif; ?>
               <!-- LISTA DE SECCIONES -->
                    <?php if(!isset($_SESSION['USER_ID'])): ?>
                         <li class="nav-item">
                              <a class="nav-link" aria-current="page" href="login">Login</a>
                         </li>
                    <?php else: ?>
                         <li class="nav-item">
                              <a class="nav-link" aria-current="page" href="logout">Logout</a>
                              <a class="nav-link" aria-current="page" href="">Agregar noticias</a>
                         </li>
                    <?php endif ?>
               </ul>
          </div>

     </nav>
</header>


<body>