<?php require('./templates/header.phtml'); ?>

<!-- form para login -->
<form action="auth" method="POST">

     <!-- correo electronico -->
     <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">Username</label>
          <input type="text" class="form-control" id="exampleFormControlInput1" required name="username">
     </div>

     <!-- password -->
     <div class="mb-3">

          <label for="inputPassword5" class="form-label">Password</label>
          <input type="password" id="inputPassword5" class="form-control" aria-describedby="passwordHelpBlock" required name="password">
          <div id="passwordHelpBlock" class="form-text">
               Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
          </div>
     </div>

     <!-- button submit -->
     <button class="btn btn-primary" type="submit">Login</button>


</form>

<?php require('./templates/footer.phtml'); ?>