<?php require('./templates/header.phtml'); ?>

<!-- form para login -->
<form action="auth" method="POST">

     <!-- correo electronico -->
     <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">Username</label>
          <input type="text" class="form-control" id="exampleFormControlInput1" required name="username">
     </div>

     <!-- password -->
     <div class="mb-3">

          <label for="inputPassword5" class="form-label">Password</label>
          <input type="password" id="inputPassword5" class="form-control" aria-describedby="passwordHelpBlock" required name="password">

     </div>

     <?php if ($error) : ?>
          <div class="alert alert-danger" role="alert">
               <?= $error ?>
          </div>
     <?php endif; ?>

     <!-- button submit -->
     <button class="btn btn-success" type="submit">Login</button>


</form>

<div class="mb-3">
     <a href="listarNoticias" class="btn btn-primary">Volver a inicio</a>
</div>
<?php require('./templates/footer.phtml'); ?>