<?php require 'templates/header.phtml' ?>


<!-- formularios para crear noticias y secciones -->
<?php if(isset($_SESSION['USER_ID'])): ?>
    <?php require 'templates/form_alta.phtml' ?>
<?php endif?>



<!-- Lista de noticias del home -->
<div class="container">
    <div class="row row-cols-1 row-cols-md-2 g-2 p-1">
        <?php foreach($newss as $news): ?>
            <div class="col border p-3">
                <a href="detalle/<?=$news->id ?>"><b><?= $news->titulo ?></b></a>
                <?php if(isset($_SESSION['USERNAME'])): ?>
                    <div class="actions">
                        <a href="eliminar/<?= $news->id ?>" type="button" class="btn btn-danger ml-auto">Borrar</a>
                    </div>
                <?php endif ?>
            </div>
        <?php endforeach ?>
    </div>
</div>

<?php require 'templates/footer.phtml' ?>
