<?php require 'templates/header.phtml' ?>


<div class="container">

    <?php if (!empty($news->id)): ?>
        <h1><?= $news->titulo ?></h1>
        <small><?= $news->fecha ?></small>
        <small><?= $news->hora ?></small>
        <div class="mt-1 p-2">
            <p class="lead"><?= $news->contenido ?></p>
        </div>

    <?php  else: ?>
        <p>La noticia no fue encontrada o no está disponible.</p>
    <?php endif ?>


</div>

<?php if (isset($_SESSION['USERNAME'])) : ?>

<?php require './templates/edit.form.news.phtml' ?>
<?php endif; ?>

<a href="../listarNoticias">Volver a Página principal</a>






<?php require 'templates/footer.phtml' ?>