    <?php require 'templates/header.phtml' ?>


    <?php if(isset($_SESSION['USER_ID'])): ?>
        <div class="container-fluid">
            <p class="h3"> Agregar noticia </p>
            <?php require 'templates/form.add.news.phtml' ?>
        </div>
        
        <div class="container-fluid">
            <p class="h3"> Agregar sección </p>
            <?php require 'templates/form.add.section.phtml' ?>
        </div>
        <div class="container-fluid">
            <?php require 'templates/sections.list.phtml' ?>
        </div>
    <?php endif?>
    



    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 g-2 p-1">
            <?php foreach($newss as $news): ?>
                <div class="col border p-3">
                    <a href="detalleNoticia/<?=$news->id ?>"><b><?= $news->titulo ?></b></a>
                    <p><?= $news->id_seccion?></p>

                    <?php if(isset($_SESSION['USER_ID'])): ?>
                        <div class="actions">
                            
                            <a href="eliminarNoticia/<?= $news->id ?>" type="button" class="btn btn-danger ml-auto">Borrar</a>
                        </div>
                    <?php endif ?>
                </div>
            <?php endforeach ?>
        </div>


</main>

<?php require 'templates/footer.phtml' ?>
