<?php require 'templates/header.phtml' ?>


<div class="container">
    
    <?php if ($news !== false) { ?>
        <?php var_dump($news) ?>
        <h1><?= $news->titulo ?></h1>
        <small><?= $news->fecha ?></small>
        <small><?= $news->hora ?></small>
        <div class="mt-1 p-2">
            <p class="lead"><?= $news->contenido ?></p>
        </div>
        
    <?php } else { ?>
        <p>La noticia no fue encontrada o no está disponible.</p>
    <?php } ?>
    
   

</div>

    <?php require 'templates/edit.form.news.phtml' ?>


        <a href="<?php echo BASE_URL?>"> Volver a Página principal</a>   
<?php require 'templates/footer.phtml' ?>