<div class="container">

     <ul class="list-group">
          <?php foreach ($sections as $section) : ?>
               <li class="list-group-items">
                    <div>
                         <?= $section->nombre_seccion ?>
                    </div>
                    <div>
                         <a href="eliminar-seccion/<?= $section->id_seccion ?>">Eliminar</a>
                         <a href="editar-seccion/<?= $section->id_seccion ?>">Editar</a>
                    </div>
               </li>
          <?php endforeach; ?>
     </ul>
</div>